---
# - name: Download Postgre SQL
#   block:
#     - name: "PreDownload Postgre N1"
#       shell: 
#         cmd: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"

#     - name: "PreDownload Postgre N2"
#       shell: 
#         cmd: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

#     - name: "Check/Install Postgresql"
#       apt: 
#         name: "postgresql"
#         state: present
#         update_cache: true
#       become: true

#     - name: "Check/Install Postgresql-contrib"
#       apt: 
#         name: "postgresql-contrib"
#         state: present
#         update_cache: true
#       become: true

- name: Rebuilding Postgre DB
  block:
    # - name: "Copy Backup File"
    #   copy: 
    #     src: /var/lib/jenkins/backup
    #     dest: /var/lib/postgresql/backup
    #     owner: postgres
    #     group: postgres
    #     mode: '0744'
    #   become: true

    # - name: "Grant User For Backup"
    #   postgresql_pg_hba:
    #     dest: /etc/postgresql/17/main/pg_hba.conf
    #     contype: local
    #     users: postgres
    #     databases: all
    #     method: trust
    #   become: true

    # - name: "Restart PSQL service"
    #   service:
    #     name: "postgresql"
    #     state: restarted
    #   become: true

    # - name: "PSQL Up DB"
    #   become_user: postgres
    #   postgresql_db:
    #     name: postgres
    #     state: restore
    #     target:  /var/lib/postgresql/backup

    - name: psycopg2 is installed
      pip3:
        name: psycopg2
        state: present

    # - name: "PSQL Up DB"
    #   become_user: postgres
    #   postgresql_user:
    #     db: postgres
    #     name: "{{ user_pg }}"
    #     password: "{{ password_pg }}"
    
    - name: "PSQL Up DB"
      become_user: postgres
      postgresql_user:
        db: postgres
        name: "{{ user_pg }}"
        password: "{{ password_pg }}"
        priv: "CONNECT/public.count_update:ALL"
        expires: "Jan 31 2026"
    
    # - name: "Grant User For Backup"
    #   postgresql_pg_hba:
    #     dest: /etc/postgresql/17/main/pg_hba.conf
    #     contype: local
    #     users: postgres
    #     databases: all
    #     method: peer
    #   become: true

    # - name: "Grant Test User"
    #   postgresql_pg_hba:
    #     dest: /etc/postgresql/17/main/pg_hba.conf
    #     contype: host
    #     users: test_user
    #     source: 0.0.0.0/0
    #     databases: postgres
    #     method: scram-sha-256
    #   become: true
    
    # - name: "Listen Addresses PSQL For App"
    #   lineinfile:
    #     dest: /etc/postgresql/17/main/postgresql.conf
    #     regexp: "listen_addresses ="
    #     line: "listen_addresses = '*'"
    #     state: present
    #   become: true

    # - name: "Restart PSQL service"
    #   service:
    #     name: "postgresql"
    #     state: restarted
    #   become: true