---
- name: Test Message
  hosts: "{{ service }}"
  roles:
    - for_test/tasks/start.yml
  tags: [ping]

- name: Ping Servers
  hosts: "{{ service }}"
  tasks:
    - name: Ping servers
      debug:
        msg: "{{ path_service }}"
    - name: Ping servers
      ping:
  tags: [deploy, update_app]

- name: Git Repo
  hosts: "{{ service }}"
  roles:
    - git
  tags: [deploy, update_app]

- name: Steps Install Docker
  hosts: "{{ service }}"
  roles:
    - docker
  tags: deploy
  
- name: Steps Install PostgreSQL
  hosts: "{{ service }}"
  roles:
    - postgresql
  tags: deploy

- name: Build app
  hosts: [test_service,service_with_postrges]
  tasks:
    - name: "Docker Build And Start App"
      shell: 
        cmd: "docker-compose up -d"
        chdir: "{{ path_service }}"
  tags: deploy

- name: Restart app after deploy
  hosts: "{{ service }}"
  tasks:
    - name: "Docker Stop"
      shell: 
        cmd: "docker-compose stop"
        chdir: "{{ path_service }}"
      ignore_errors: yes
    - name: "Docker Start"
      shell: 
        cmd: "docker-compose start"
        chdir: "{{ path_service }}"
  tags: update_app