---
- name: Ping Servers
  hosts: "{{ service }}"
  tasks:
    - name: Ping servers
      ping:

- name: Git Repo
  hosts: "{{ service }}"
  roles:
    - git

- name: Deploy And App
  hosts: "{{ service }}"
  tasks:
    - name: Deploy And App Service
      included_tasks: "{{ service }}.yml"