---
- name: Ping Servers
  hosts: [test_service,service_with_postrges]
  tasks:
    - name: Ping servers
      ping:

- name: GIT
  hosts: [test_service,service_with_postrges]
  tasks:
    - name: "Git clone repo"
      git:
        repo: "{{ git_repo }}"
        dest: "{{ path_service }}"
        clone: yes
        update: yes

- name: Steps Install Docker
  hosts: [test_service,service_with_postrges]
  roles:
    - docker
  
- name: Steps Install PostgreSQL
  hosts: [service_with_postrges]
  roles:
    - postgresql

- name: Build app
  hosts: [test_service,service_with_postrges]
  tasks:
    - name: "Docker Build And Start App"
      shell: 
        cmd: "docker-compose up -d"
        chdir: "{{ path_service }}"