---
- name: Ping Servers
  hosts: "{{ service }}"
  tasks:
    - name: Ping servers
      ping:

- name: Git Repo
  hosts: "{{ service }}"
  roles:
    - git

- name: Deploy And App Service
  hosts: "{{ service }}"
  include:
    - "{{ service }}".yml