---
- name: Ping Servers
  hosts: main_group
  tasks:
    - name: Ping servers
      ping:
  tags: [configure, deploy, check]

- name: GIT
  hosts: main_group
  tasks:
    - name: "Git clone repo"
      git:
        repo: https://github.com/JackSpades17/test_service
        dest: "{{ path_service }}"
        clone: yes
        update: yes
  tags: [configure, deploy]

- name: Install Docker
  hosts: main_group
  tasks:
    - name: update and upgrade apt
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Check/Install docker"
      apt: 
        name: "docker.io"
        state: present
        update_cache: true
      become: true

    - name: "Check/Install docker-compose"
      apt: 
        name: "docker-compose"
        state: present
        update_cache: true
      become: true

    # - name: "Usermod USER"
    #   become: true
    #   user: 
    #     name: "{{ansible_user}}"
    #     group: docker
    #     append: yes

    - name: "Start docker service"
      service:
        name: "docker"
        state: started
      become: yes
  tags: configure

- name: Restart app after deploy
  hosts: main_group
  tasks:
    - name: "Docker Stop"
      shell: 
        cmd: "sudo docker-compose stop"
        chdir: "{{ path_service }}"
      ignore_errors: yes
    - name: "Docker Start"
      shell: 
        cmd: "sudo docker-compose start"
        chdir: "{{ path_service }}"
  tags: deploy

- name: Build app
  hosts: main_group
  tasks:
    - name: "Docker Build"
      shell: 
        cmd: "sudo docker build -f Dockerfile -t test_zone ."
        chdir: "{{ path_service }}"
  tags: configure

- name: Start app
  hosts: main_group
  tasks:
    - name: "Start app in Docker"
      shell: 
        cmd: "sudo docker-compose up -d"
        chdir: "{{ path_service }}"
  tags: configure


    
  

