---
- name: Ping Servers
  hosts: localhost
  tasks:

  - name: Ping servers
    ping:

  - name: check Linux
    shell: "echo {{ ansible_lsb.id }}"
    register: check2

  - name: 
    shell: "echo {{ ansible_os_family }}"
    register: check1

  - name: Echo
    shell: "echo 1111"
    register: check
    when: ansible_os_family == "Debian"

  # - name: SSH check
  #   shell: "echo ssh"
  #   notify: Restart SSH

  - name: Debug
    debug: var=check

  - name: Echo
    shell: "echo 2222"
    register: check

  # - name: SSH check
  #   shell: "echo ssh"
  #   notify: Restart SSH

  tags: ping

  # handlers:
  # - name: Restart SSH
  #   service: name=sshd state=restarted
  #   become: yes
