---
- name: Ping Servers
  hosts: test
  tasks:
  - name: Ping servers
    ping:

  - name: Echo
    shell: "echo 1111"
    register: check

  # - name: SSH check
  #   shell: "echo ssh"
  #   notify: Restart SSH

  - name: Debug
    debug: var=check

  - name: Echo
    shell: "echo 2222"
    register: check

  # - name: SSH check
  #   shell: "echo ssh"
  #   notify: Restart SSH

  tags: ping

  # handlers:
  # - name: Restart SSH
  #   service: name=sshd state=restarted
  #   become: yes
