---
- name: Ping Servers
  hosts: "{{ service }}"
  tasks:
    - name: Ping servers
      ping:

- name: Git Repo
  hosts: "{{ service }}"
  roles:
    - git

- name: Steps Install Docker
  hosts: "{{ service }}"
  roles:
    - docker
  tags: deploy

- name: Build app
  hosts: "{{ service }}"
  tasks:
    - name: Build App
      include_role:
        name: docker
        tasks_from: build_app
  tags: deploy

- name: Steps Restart Docker
  hosts: "{{ service }}"
  tasks:
    - name: Restart App
      include_role:
        name: docker
        tasks_from: reload_app
  tags: update_app