---
- name: Install Docker
  block:
    - name: Update And Upgrade Apt
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Check/Install Docker"
      apt: 
        name: "docker.io"
        state: present
        update_cache: true

    - name: "Check/Install Docker-compose"
      apt: 
        name: "docker-compose"
        state: present
        update_cache: true

    - name: "Start docker service"
      service:
        name: "docker"
        state: started

    - name: "Change Role User For Docker"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Rebooting Machine
      reboot:
        reboot_timeout: 120
        msg: "Rebooting machines"
  become: true