---
- name: Service With Postgres Install
  block:
    # - name: Ping servers
    #   ping:
    #   tags: [ping, deploy, update_app]

    - name: Git Repo
      roles:
       - git
      tags: [ping, deploy, update_app]
    
    - name: Test message
      debug:
        msg: 'Test'
      tags: ping

    # - name: Steps Install Docker
    #   roles:
    #     - docker
    #   tags: deploy
      
    # - name: Steps Install PostgreSQL
    #   roles:
    #     - postgresql
    #   tags: deploy

    # - name: Build app
    #   tasks:
    #     - name: Build App
    #       include_role:
    #         name: docker
    #         tasks_from: build_app
    #   tags: deploy

    # - name: Restart app after deploy
    #   tasks:
    #     - name: Restart App
    #       include_role:
    #         name: docker
    #         tasks_from: reload_app
    #   tags: update_app